RoverTX: RUNNING Class Reference
RUNNING Class Reference
#include <running.hpp>
Public Member Functions
RUNNING ()
~RUNNING ()
int checkEscape (char &dir)
int checkKeyPressed ()
int checkQuit ()
int checkValues (int &direction, int &side, int &speed, int &freq, int &t)
void stopSensorsRunning ()
int runRemote ()
void runFollow ()
void runEscape ()
Public Attributes
SENSORS * sensors
DRIVE * drive
Detailed Description
Definition at line 20 of file running.hpp.
Constructor & Destructor Documentation
RUNNING()
RUNNING::RUNNING ()
Creates a new RUNNING and initializes sensors and drive
Definition at line 20 of file running.cpp.
References drive, and sensors.
~RUNNING()
RUNNING::~RUNNING ()
Definition at line 25 of file running.cpp.
Member Function Documentation
checkEscape()
int RUNNING::checkEscape (char & dir)
detect if escape condition appeared. Escape condition is typed in X
Definition at line 28 of file running.cpp.
References escape.
Referenced by checkValues().
checkKeyPressed()
int RUNNING::checkKeyPressed ()
implement if key pressed during running return: if escape key pressed return escape condition, else return pressed key TODO: implement check functionality for pressed key without enter
Definition at line 37 of file running.cpp.
References escape.
Referenced by checkQuit().
checkQuit()
int RUNNING::checkQuit ()
detect if any problem or escape condition is appeared return: 0 if no problem else 1
Definition at line 48 of file running.cpp.
References DRIVE::checkError(), checkKeyPressed(), and drive.
Referenced by runEscape(), and runFollow().
checkValues()
int RUNNING::checkValues (int & direction, int & side, int & speed, int & freq, int & t)
check all entered values as integers direction: adress of direction side: adress of side speed: adress of speed freq: adress of freq t: adress of t (time) return: 1, if all entries valide, escape, if escape condition entered or else 0
Definition at line 55 of file running.cpp.
References checkEscape(), and escape.
Referenced by runRemote().
runEscape()
void RUNNING::runEscape ()
run the escape mode. checks via sensors values if the movement is allowed and depend of the sensor values it runs the intelligentEscaping
Definition at line 137 of file running.cpp.
References checkQuit(), defaultFrequenz, drive, front, DRIVE::intelligentEscaping(), nospeedchange, SENSORS::readDistance(), rear, and sensors.
runFollow()
void RUNNING::runFollow ()
run the follow mode. checks via sensors values if the movement is allowed and depend of the sensor values it runs the intelligentFollowing
Definition at line 121 of file running.cpp.
References checkQuit(), defaultFrequenz, drive, front, DRIVE::intelligentFollowing(), nospeedchange, SENSORS::readDistance(), rear, and sensors.
runRemote()
int RUNNING::runRemote ()
to run the remote mode. checks via sensors values if the movement is allowed and runs via remoteControl if the entered values are correct for moving the motors
Definition at line 89 of file running.cpp.
References checkValues(), drive, escape, front, SENSORS::readDistance(), rear, DRIVE::remoteControl(), and sensors.
stopSensorsRunning()
void RUNNING::stopSensorsRunning ()
to stop the sensor Running via deinitialisation
Definition at line 85 of file running.cpp.
References SENSORS::deinitSensors(), and sensors.
Member Data Documentation
drive
DRIVE* RUNNING::drive
drive object pointer for accessing the drive functionality
Definition at line 30 of file running.hpp.
Referenced by checkQuit(), runEscape(), runFollow(), RUNNING(), and runRemote().
sensors
SENSORS* RUNNING::sensors
sensors object pointer for accesing the sensors and their functionality
Definition at line 26 of file running.hpp.
Referenced by runEscape(), runFollow(), RUNNING(), runRemote(), and stopSensorsRunning().
The documentation for this class was generated from the following files:
running.hpp
running.cpp