RoverTX: DRIVE Class Reference
DRIVE Class Reference
#include <drive.hpp>
Public Member Functions
DRIVE ()
~DRIVE ()
int checkError (void)
void drive (int direction, int speed, int freq)
void forwardSideDriving (int direction, int speed, int freq)
void backwardSideDriving (int direction, int speed, int freq)
int intelligentEscaping (int frontDistance, int rearDistance, int speed, int freq)
int intelligentFollowing (int frontDistance, int rearDistance, int speed, int freq)
int remoteControl (int &dir, int &side, int &speed, int &freq, int &t)
int valideRemote (int &dir, int &side, int &time)
Public Attributes
MOTORSHIELD * motorshield
Detailed Description
Definition at line 14 of file drive.hpp.
Constructor & Destructor Documentation
DRIVE()
DRIVE::DRIVE ()
Creates a new DRIVE, initialisation of motorshield to get access for driving
Definition at line 20 of file drive.cpp.
References MOTORSHIELD::activateMotors(), and motorshield.
~DRIVE()
DRIVE::~DRIVE ()
Definition at line 25 of file drive.cpp.
Member Function Documentation
backwardSideDriving()
void DRIVE::backwardSideDriving (int direction, int speed, int freq)
drive function for using both motors with same parameters side: side of the motor to run speed: to increase the default speed with this value (0-240) freq: used frequenz for pwm signal
Definition at line 54 of file drive.cpp.
References drive_backward, drive_left, drive_right, left_motor_direction, motorshield, MOTORSHIELD::oneMotor(), MOTORSHIELD::pwmDriver, and right_motor_direction.
Referenced by remoteControl().
checkError()
int DRIVE::checkError (void)
detect if the initialisation problems of motorshield return: 0 if no problems, else 01
Definition at line 28 of file drive.cpp.
References MOTORSHIELD::checkError(), and motorshield.
Referenced by RUNNING::checkQuit().
drive()
void DRIVE::drive (int direction, int speed, int freq)
drive function for using both motors with same parameters direction: sets the direction to rotate speed: to increase the default speed with this value (0-240) freq: used frequenz for pwm signal
Definition at line 35 of file drive.cpp.
References MOTORSHIELD::bothMotor(), and motorshield.
Referenced by intelligentEscaping(), intelligentFollowing(), and remoteControl().
forwardSideDriving()
void DRIVE::forwardSideDriving (int direction, int speed, int freq)
for forward side driving depend on the input parameter side driving left or right will be executed side: side of the motor to run speed:to increase the default speed with this value (0-240) freq:used frequenz for pwm signal
Definition at line 39 of file drive.cpp.
References drive_forward, drive_left, drive_right, left_motor_direction, motorshield, MOTORSHIELD::oneMotor(), MOTORSHIELD::pwmDriver, and right_motor_direction.
Referenced by remoteControl().
intelligentEscaping()
int DRIVE::intelligentEscaping (int frontDistance, int rearDistance, int speed, int freq)
detect via input sensors values (distance) which direction to rotate, which frequenz to use for escaping frontDistance: front sensor value rearDistance: rear sensors value speed:to increase the default speed with this value (0-240) freq:used frequenz for pwm signal
Definition at line 70 of file drive.cpp.
References defaultFrequenz, drive(), drive_backward, drive_forward, low_f, motorshield, and MOTORSHIELD::turnOffMotors().
Referenced by RUNNING::runEscape().
intelligentFollowing()
int DRIVE::intelligentFollowing (int frontDistance, int rearDistance, int speed, int freq)
detect via input sensors values (distance) which direction to rotate, which frequenz to use for following frontDistance: front sensor value rearDistance: rear sensors value speed:to increase the default speed with this value (0-240) freq:used frequenz for pwm signal
Definition at line 109 of file drive.cpp.
References MOTORSHIELD::beeping(), defaultFrequenz, drive(), drive_backward, drive_forward, low_f, motorshield, and MOTORSHIELD::turnOffMotors().
Referenced by RUNNING::runFollow().
remoteControl()
int DRIVE::remoteControl (int & dir, int & side, int & speed, int & freq, int & t)
detect via input sensors values (distance) which direction to rotate, which frequenz to use for escaping f: front sensor value r: rear sensors value speed:to increase the default speed with this value (0-240) freq:used frequenz for pwm signal
Definition at line 148 of file drive.cpp.
References backwardSideDriving(), drive(), drive_backward, drive_forward, forwardSideDriving(), motorshield, MOTORSHIELD::turnOffMotors(), and valideRemote().
Referenced by RUNNING::runRemote().
valideRemote()
int DRIVE::valideRemote (int & dir, int & side, int & time)
check if entered values are valide dir: direction for movement parameter side: side direction for movement time: time of moving
Definition at line 166 of file drive.cpp.
References drive_backward, drive_forward, and drive_right.
Referenced by remoteControl().
Member Data Documentation
motorshield
MOTORSHIELD* DRIVE::motorshield
motorshield object pointer for accessing motor move functions
Definition at line 20 of file drive.hpp.
Referenced by backwardSideDriving(), checkError(), DRIVE(), drive(), forwardSideDriving(), intelligentEscaping(), intelligentFollowing(), and remoteControl().
The documentation for this class was generated from the following files:
drive.hpp
drive.cpp