RoverTX: SENSORS Class Reference
SENSORS Class Reference
#include <sensors.hpp>
Public Member Functions
SENSORS ()
~SENSORS ()
void initSensors ()
void deinitSensors ()
void initButtons (jetsonGPIO gpio)
int readButtons (jetsonGPIO gpio)
int readDistance (char sensor)
Public Attributes
HCSR04 * hcsr04Front
HCSR04 * hcsr04Rear
jetsonGPIO usr_button
jetsonGPIO shutdown_button
Detailed Description
Definition at line 15 of file sensors.hpp.
Constructor & Destructor Documentation
SENSORS()
SENSORS::SENSORS ()
Creates a new SENSORS, initialisation of all Sensors and used GPIOs to get access for reading of values and changes
Definition at line 22 of file sensors.cpp.
References gpio12, gpio13, gpio31, gpio37, hcsr04Front, hcsr04Rear, and initSensors().
~SENSORS()
SENSORS::~SENSORS ()
Definition at line 31 of file sensors.cpp.
Member Function Documentation
deinitSensors()
void SENSORS::deinitSensors ()
deinitialisation of used sensors
Definition at line 46 of file sensors.cpp.
References hcsr04Front, and hcsr04Rear.
Referenced by RUNNING::stopSensorsRunning().
initButtons()
void SENSORS::initButtons (jetsonGPIO gpio)
initialisation of button for used gpio gpio: gpio adress of button
Definition at line 51 of file sensors.cpp.
Referenced by readButtons().
initSensors()
void SENSORS::initSensors ()
initialisation of the used sensors includes export and direction set for required gpios of sensors
Definition at line 35 of file sensors.cpp.
References hcsr04Front, and hcsr04Rear.
Referenced by SENSORS().
readButtons()
int SENSORS::readButtons (jetsonGPIO gpio)
read values of # gpio: gpio adress of button return: value of read button
Definition at line 57 of file sensors.cpp.
References initButtons().
readDistance()
int SENSORS::readDistance (char sensor)
read distance of ultrasonic sensor, depend on input of sensor name sensor: sensor short name return: range of measured distance in cm
Definition at line 65 of file sensors.cpp.
References hcsr04Front, and hcsr04Rear.
Referenced by RUNNING::runEscape(), RUNNING::runFollow(), and RUNNING::runRemote().
Member Data Documentation
hcsr04Front
HCSR04* SENSORS::hcsr04Front
pointer on object of front HCSR04 ultrasonic sensor module
Definition at line 21 of file sensors.hpp.
Referenced by deinitSensors(), initSensors(), readDistance(), and SENSORS().
hcsr04Rear
HCSR04* SENSORS::hcsr04Rear
pointer on object of rear HCSR04 ultrasonic sensor module
Definition at line 25 of file sensors.hpp.
Referenced by deinitSensors(), initSensors(), readDistance(), and SENSORS().
shutdown_button
jetsonGPIO SENSORS::shutdown_button
GPIO adress of shutdown_button
Definition at line 33 of file sensors.hpp.
usr_button
jetsonGPIO SENSORS::usr_button
GPIO adress of usr_button
Definition at line 29 of file sensors.hpp.
The documentation for this class was generated from the following files:
sensors.hpp
sensors.cpp