RoverTX: MOTORSHIELD Class Reference
MOTORSHIELD Class Reference
#include <motorShield.hpp>
Public Member Functions
MOTORSHIELD ()
~MOTORSHIELD ()
void setUsedGPIOS (void)
void unsetUsedGPIOS (void)
void activateMotors (void)
void initPwmDriver (void)
void deactivateMotors (void)
void stopMoving (void)
int checkError (void)
void beeping (int time)
int checkRunningMotor (void)
void turnOffMotors (void)
void turnOnMotors (void)
void oneMotor (int motorDirectionPin, int dir, int speed, int freq)
void bothMotor (int dir, int speed, int freq)
Public Attributes
jetsonGPIO enableMotors
jetsonGPIO leftDirection
jetsonGPIO rightDirection
jetsonGPIO buzzer
PCA9685 * pwmDriver
int motorState
Detailed Description
Definition at line 50 of file motorShield.hpp.
Constructor & Destructor Documentation
MOTORSHIELD()
MOTORSHIELD::MOTORSHIELD ()
Creates a new MOTORSHIELD. Sets the adress for the used gpio pins and the current motorState and also the initialisation of pwm driver to get access for pwm functionality
Definition at line 21 of file motorShield.cpp.
References buzzer, buzzer_signal, enable_motor, enableMotors, left_motor_direction, leftDirection, motorState, pwmDriver, right_motor_direction, and rightDirection.
~MOTORSHIELD()
MOTORSHIELD::~MOTORSHIELD ()
Definition at line 30 of file motorShield.cpp.
Member Function Documentation
activateMotors()
void MOTORSHIELD::activateMotors (void)
initalisation of used GPIOs and pwm driver for the actiovation of motors to allow the driving
Definition at line 52 of file motorShield.cpp.
References initPwmDriver(), setUsedGPIOS(), and unsetUsedGPIOS().
Referenced by DRIVE::DRIVE().
beeping()
void MOTORSHIELD::beeping (int time)
set buzzer for a specififc time time: specific running time
Definition at line 94 of file motorShield.cpp.
References buzzer.
Referenced by DRIVE::intelligentFollowing().
bothMotor()
void MOTORSHIELD::bothMotor (int dir, int speed, int freq)
rotating both motors. Rotation behaviour depends on input parameters dir: sets the direction to rotate speed: to increase the default speed with this value (0-240) freq: used frequenz for pwm signal
Definition at line 158 of file motorShield.cpp.
References drive_backward, drive_forward, fast_backward, fast_forward, left_motor_direction, pwmDriver, right_motor_direction, slow_backward, slow_forward, and turnOnMotors().
Referenced by DRIVE::drive().
checkError()
int MOTORSHIELD::checkError (void)
detect if pwm driver of motorshield has initialisation problems return: 1 if problem, else 0
Definition at line 82 of file motorShield.cpp.
References pwmDriver.
Referenced by DRIVE::checkError().
checkRunningMotor()
int MOTORSHIELD::checkRunningMotor (void)
check the current motor state return: 1 if already active, else 0
Definition at line 100 of file motorShield.cpp.
References motorState.
Referenced by turnOnMotors().
deactivateMotors()
void MOTORSHIELD::deactivateMotors (void)
deactivate the used pwm driver and the motors
Definition at line 71 of file motorShield.cpp.
References pwmDriver, and unsetUsedGPIOS().
initPwmDriver()
void MOTORSHIELD::initPwmDriver (void)
initialisation of pwm driver. Required for generation of pwm signals
Definition at line 58 of file motorShield.cpp.
References pwmDriver.
Referenced by activateMotors().
oneMotor()
void MOTORSHIELD::oneMotor (int motorDirectionPin, int dir, int speed, int freq)
rotating one motor. Rotation behaviour depends on input parameters motorDirectionPin: sets the motor to rotate dir: sets the direction to rotate speed: to increase the default speed with this value (0-240) freq: used frequenz for pwm signal
Definition at line 127 of file motorShield.cpp.
References drive_backward, drive_forward, fast_backward, fast_forward, left_motor_direction, leftmotor, pwmDriver, right_motor_direction, rightmotor, slow_backward, slow_forward, and turnOnMotors().
Referenced by DRIVE::backwardSideDriving(), and DRIVE::forwardSideDriving().
setUsedGPIOS()
void MOTORSHIELD::setUsedGPIOS (void)
set up the used GPIO pins MOTORSHIELD.
Definition at line 34 of file motorShield.cpp.
References buzzer, enableMotors, leftDirection, and rightDirection.
Referenced by activateMotors().
stopMoving()
void MOTORSHIELD::stopMoving (void)
stop the moving with no pwm signal
Definition at line 76 of file motorShield.cpp.
References drive_backward, left_motor_direction, pwmDriver, and right_motor_direction.
Referenced by turnOffMotors().
turnOffMotors()
void MOTORSHIELD::turnOffMotors (void)
turning off motors and pwm signal
Definition at line 107 of file motorShield.cpp.
References enableMotors, motorState, and stopMoving().
Referenced by DRIVE::intelligentEscaping(), DRIVE::intelligentFollowing(), and DRIVE::remoteControl().
turnOnMotors()
void MOTORSHIELD::turnOnMotors (void)
turning on motors and set current motorState
Definition at line 115 of file motorShield.cpp.
References checkRunningMotor(), enableMotors, and motorState.
Referenced by bothMotor(), and oneMotor().
unsetUsedGPIOS()
void MOTORSHIELD::unsetUsedGPIOS (void)
unset the used GPIO pins MOTORSHIELD.
Definition at line 45 of file motorShield.cpp.
References buzzer, enableMotors, leftDirection, and rightDirection.
Referenced by activateMotors(), and deactivateMotors().
Member Data Documentation
buzzer
jetsonGPIO MOTORSHIELD::buzzer
gpio pin of connected buzzer
Definition at line 68 of file motorShield.hpp.
Referenced by beeping(), MOTORSHIELD(), setUsedGPIOS(), and unsetUsedGPIOS().
enableMotors
jetsonGPIO MOTORSHIELD::enableMotors
gpio pin to activate or deactivate motors
Definition at line 56 of file motorShield.hpp.
Referenced by MOTORSHIELD(), setUsedGPIOS(), turnOffMotors(), turnOnMotors(), and unsetUsedGPIOS().
leftDirection
jetsonGPIO MOTORSHIELD::leftDirection
gpio pin to setDirection for left motor
Definition at line 60 of file motorShield.hpp.
Referenced by MOTORSHIELD(), setUsedGPIOS(), and unsetUsedGPIOS().
motorState
int MOTORSHIELD::motorState
current motorState
Definition at line 76 of file motorShield.hpp.
Referenced by checkRunningMotor(), MOTORSHIELD(), turnOffMotors(), and turnOnMotors().
pwmDriver
PCA9685* MOTORSHIELD::pwmDriver
pwm driver object pointer to get access for pwm functionality
Definition at line 72 of file motorShield.hpp.
Referenced by DRIVE::backwardSideDriving(), bothMotor(), checkError(), deactivateMotors(), DRIVE::forwardSideDriving(), initPwmDriver(), MOTORSHIELD(), oneMotor(), and stopMoving().
rightDirection
jetsonGPIO MOTORSHIELD::rightDirection
gpio pin to setDirection for right motor
Definition at line 64 of file motorShield.hpp.
Referenced by MOTORSHIELD(), setUsedGPIOS(), and unsetUsedGPIOS().
The documentation for this class was generated from the following files:
motorShield.hpp
motorShield.cpp